# Generated by Django 5.2.7 on 2025-12-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0005_remove_character_model'),
        ('training', '0004_trainedmodel_job_id_alter_trainedmodel_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('quote', models.TextField()),
                ('is_safe', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_quotes', to='scraper.character')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_urls_discovered', models.IntegerField(default=0)),
                ('unsafe_quotes_extracted', models.IntegerField(default=0)),
                ('safe_quotes_extracted', models.IntegerField(default=0)),
                ('unique_quotes', models.IntegerField(default=0)),
                ('scrape_duration', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_metrics', to='scraper.character')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quotes_used', models.IntegerField(default=0)),
                ('dataset_size_kb', models.FloatField(default=0.0)),
                ('fine_tune_start', models.DateTimeField(blank=True, null=True)),
                ('fine_tune_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(default=0.0)),
                ('job_status', models.CharField(default='pending', max_length=50)),
                ('final_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trained_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainedmodel')),
            ],
        ),
    ]
