# Generated by Django 5.2.7 on 2025-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmetrics',
            name='quotes_removed',
            field=models.IntegerField(default=0),
        ),
    ]
