# Generated by Django 5.2.7 on 2025-12-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_trainingmetrics_quotes_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmetrics',
            name='rewritten_preview',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
