# Generated by Django 5.2.7 on 2025-12-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_trainingmetrics_rewritten_preview'),
        ('scraper', '0005_remove_character_model'),
        ('training', '0004_trainedmodel_job_id_alter_trainedmodel_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewrittenQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quote', models.TextField()),
                ('rewritten_quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewritten_quotes', to='scraper.character')),
                ('trained_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewritten_quotes', to='training.trainedmodel')),
            ],
        ),
    ]
