# Generated by Django 5.2.7 on 2025-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
