# Generated by Django 5.2.7 on 2025-11-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage'),
        ('scraper', '0005_remove_character_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='scraper.character'),
        ),
    ]
