# Generated by Django 5.2.7 on 2025-11-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_character'),
        ('training', '0004_trainedmodel_job_id_alter_trainedmodel_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.trainedmodel'),
        ),
    ]
