# Generated by Django 5.2.7 on 2025-11-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
        ('training', '0002_remove_trainedmodel_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='model_id',
        ),
        migrations.AddField(
            model_name='character',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='training.trainedmodel'),
        ),
    ]
