# Generated by Django 5.2.7 on 2025-11-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_character_dataset_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
