# Generated by Django 5.2.7 on 2025-11-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_character_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='model',
        ),
    ]
