# Generated by Django 5.2.7 on 2025-11-16 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255, unique=True)),
                ('training_status', models.CharField(default='pending', max_length=50)),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trained_model', to='scraper.character')),
            ],
        ),
    ]
