# Generated by Django 5.2.7 on 2025-11-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_character_model'),
        ('training', '0002_remove_trainedmodel_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='scraper.character'),
        ),
    ]
