# Generated by Django 5.2.7 on 2025-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainedmodel_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
